<?php $reviewCollection = $block->getCollection(); ?>
<?php if (count($reviewCollection)): ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getEditAction() ?>" class="review-form" method="post" id="review-form" data-mage-init='{"validation":{}}' data-role="product-review-form" data-bind="scope: 'review-form'">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
        <legend class="legend review-legend"><span><?php /* @escapeNotVerified */ echo __("You're reviewing:"); ?></span><strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend><br />
        <?php foreach ($reviewCollection as $_r): ?>
            <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                <fieldset class="field required review-field-ratings" data-hasrequired="<?php __('* Required Fields'); ?>">
                    <legend class="label"><span><?php /* @escapeNotVerified */ echo __('Your Rating') ?></span></legend><br/>
                    <div class="control">
                        <div class="nested" id="product-review-table">
                            <?php foreach ($block->getRatings() as $_rating): ?>
                                <div class="field choice review-field-rating">
                                    <label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                    <div class="control review-control-vote">
                                        <?php $options = $_rating->getOptions();?>
                                        <?php $iterator = 1; foreach ($options as $_option): ?>
                                            <input
                                                    type="radio"
                                                    name="ratings[<?php /* @escapeNotVerified */ echo $_rating->getId() ?>]"
                                                    id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                                    value="<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                                                    class="radio"
                                                    data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                                    <?php if ($block->isSelected($_option, $_rating)): ?>checked="checked"<?php endif; ?>
                                                    aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label" />
                                            <label
                                                    class="rating-<?php /* @escapeNotVerified */ echo $iterator; ?>"
                                                    for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
                                                    title="<?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                                    id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label">
                                                <span><?php /* @escapeNotVerified */ echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                            </label>
                                            <?php $iterator++; ?>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                    </div>
                </fieldset>
            <?php endif ?>
            <input type="hidden" name="id" value="<?= $_r->getReviewId(); ?>">
            <input type="hidden" name="proId" value="<?= $block->getProductInfo()->getId(); ?>">
            <div class="field review-field-nickname required">
                <label for="nickname_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Nickname') ?></span></label>
                <div class="control">
                    <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}"  value="<?php echo $_r->getNickname(); ?>" />
                </div>
            </div>
            <div class="field review-field-summary required">
                <label for="summary_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Summary') ?></span></label>
                <div class="control">
                    <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" value="<?php echo $_r->getTitle(); ?>"/>
                </div>
            </div>
            <div class="field review-field-text required">
                <label for="review_field" class="label"><span><?php /* @escapeNotVerified */ echo __('Review') ?></span></label>
                <div class="control">
                    <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}"><?php echo $_r->getDetail(); ?></textarea>
                </div>
            </div>
        <?php endforeach ?>
    </fieldset>
    <div class="actions-toolbar review-form-actions review-form-actions-popup">
        <div class="primary actions-primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit Review') ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {}
    }
}
</script>
<?php else: ?>
    <div class="message error">
        <div><?= __('The review was removed or does not exist.') ?></div>
    </div>
<?php endif ?>
