<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php /** @var $block \Amasty\RequestQuote\Block\Adminhtml\Quote\View\Tab\Info */ ?>
<?php $quote = $block->getQuote() ?>

<div id="order-messages">
    <?= $block->getChildHtml('order_messages') ?>
</div>

<?= $block->getChildHtml('quote_info') ?>
<input type="hidden" name="order_id" value="<?= $block->escapeHtml($quote->getId()) ?>"/>

<?= $block->getChildHtml('order_additional_info') ?>

<?= $block->getGiftOptionsHtml() ?>

<div id="quote-search" style="display: none" class="admin__page-section quote-search-items">
    <?= $block->getChildHtml('search') ?>
</div>

<section class="admin__page-section" id="quote-items">
    <?= $block->getItemsHtml() ?>

    <?php if ((int)$block->getAppliedDiscount()) : ?>
        <p class="amquote-line-block -total">
            <?= $block->escapeHtml(__('Applied discount') . ': ') ?>
            <strong><?= $block->escapeHtml($block->getAppliedDiscount() . '%') ?></strong>
        </p>
    <?php endif; ?>
    <?php if ((int)$block->getAppliedSurcharge()) : ?>
        <p class="amquote-line-block -total">
            <?= $block->escapeHtml(__('Applied surcharge') . ': ') ?>
            <strong><?= $block->escapeHtml($block->getAppliedSurcharge() . '%') ?></strong>
        </p>
    <?php endif; ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Quote Total')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Remarks for this Quote')) ?></span>
            </div>
            <?= $block->getChildHtml('quote_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Quote Totals')) ?></span>
            </div>
            <?= $block->getChildHtml('quote_totals') ?>
        </div>
    </div>
</section>

