<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php if ($block->displayBoth()):?>
<tr class="row-totals">
    <td style="<?= /* @escapeNotVerified */ $block->getStyle() ?>" class="admin__total-mark" colspan="<?= /* @escapeNotVerified */ $block->getColspan() ?>">
        <?= /* @escapeNotVerified */ __('Subtotal (Excl. Tax)') ?>
    </td>
    <td style="<?= /* @escapeNotVerified */ $block->getStyle() ?>" class="admin__total-amount">
        <?= /* @escapeNotVerified */ $block->formatPrice($block->getTotal()->getValueExclTax()) ?>
    </td>
</tr>
<tr class="row-totals">
    <td style="<?= /* @escapeNotVerified */ $block->getStyle() ?>" class="admin__total-mark" colspan="<?= /* @escapeNotVerified */ $block->getColspan() ?>">
        <?= /* @escapeNotVerified */ __('Subtotal (Incl. Tax)') ?>
    </td>
    <td style="<?= /* @escapeNotVerified */ $block->getStyle() ?>" class="admin__total-amount">
        <?= /* @escapeNotVerified */ $block->formatPrice($block->getTotal()->getValueInclTax()) ?>
    </td>
</tr>
<?php else : ?>
<tr class="row-totals">
    <td style="<?= /* @escapeNotVerified */ $block->getStyle() ?>" class="admin__total-mark" colspan="<?= /* @escapeNotVerified */ $block->getColspan() ?>">
        <?= /* @escapeNotVerified */ $block->getTotal()->getTitle() ?>
    </td>
    <td style="<?= /* @escapeNotVerified */ $block->getStyle() ?>" class="admin__total-amount">
        <?= /* @escapeNotVerified */ $block->formatPrice($block->getTotal()->getValue()) ?>
    </td>
</tr>
<?php endif;?>
