<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/** @var \Amasty\RequestQuote\Block\Cart\Quote\Link $block */
?>
<button type="button"
        data-role="proceed-to-checkout"
        title="<?= /* @escapeNotVerified */
        __('Submit Quote') ?>"
        data-mage-init='{"Amasty_RequestQuote/js/quote/submit":{}}'
        class="action primary checkout"
    <span><?= /* @escapeNotVerified */
        __('Submit Quote') ?></span>
</button>
