<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/** @var \Amasty\RequestQuote\Block\Adminhtml\Quote\View\Items\Renderer\DefaultRenderer $block */
$quote = $block->getQuote() ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <?php $i = 0;
                $columns = $block->getColumns();
                $lastItemNumber = count($columns) ?>
                <?php foreach ($columns as $columnName => $columnTitle) : ?>
                    <?php $i++; ?>
                    <th class="col-<?= /* @noEscape */ $columnName ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"><span><?= /* @noEscape */ $columnTitle ?></span></th>
                <?php endforeach; ?>
            </tr>
        </thead>
        <?php $items = $block->getItemsCollection();?>
        <?php $i = 0; foreach ($items as $item) : ?>
            <?php if ($item->getParentItem()) {
                continue;
            } else {
                $i++;
            }?>
            <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
                <?= $block->getItemHtml($item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
