<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
// @codingStandardsIgnoreFile
 ?>

<?php /* <h4 class="icon-head fieldset-legend <?= $block->getHeaderCssClass() ?>"><?= $block->getHeaderText() ?></h4> */ ?>
<div class="admin__field field-comment">
    <label for="order-comment" class="admin__field-label"><span><?= /* @escapeNotVerified */ __('Quote Comments') ?></span></label>
    <div class="admin__field-control">
        <textarea
            id="order-comment"
            name="quote[note]"
            class="admin__control-textarea"><?= /* @escapeNotVerified */ $block->getCommentNote() ?></textarea>
    </div>
</div>
<script>
    require(["Amasty_RequestQuote/quote/create/form"], function(){
        quote.commentFieldsBind('order-comment')
    });
</script>
