<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/** @var \Amasty\RequestQuote\Block\Adminhtml\Quote\Create\Data $block */

// @codingStandardsIgnoreFile

?>
<div class="page-create-order">
    <script>
        require(["Amasty_RequestQuote/quote/create/form"], function(){
            quote.setCurrencySymbol('<?= /* @escapeNotVerified */ $block->getCurrencySymbol($block->getCurrentCurrencyCode()) ?>')
        });
    </script>
    <div class="order-details<?php if ($block->getCustomerId()): ?> order-details-existing-customer<?php endif; ?>">

        <div id="order-additional_area" style="display: none" class="admin__page-section order-additional-area">
            <?= $block->getChildHtml('additional_area') ?>
        </div>

        <div id="quote-search" style="display: none" class="admin__page-section order-search-items">
            <?= $block->getChildHtml('search') ?>
        </div>

        <section id="quote-items" class="admin__page-section order-items" data-mage-init='{"loader": {}}'>
            <?= $block->getChildHtml('items') ?>
        </section>

        <div id="order-errors" class="order-errors"><?= $block->getChildHtml('errors') ?></div>

        <section id="order-form_account" class="admin__page-section order-account-information">
            <?= $block->getChildHtml('form_account') ?>
        </section>

        <?php if ($block->getChildBlock('card_validation')): ?>
            <section id="order-card_validation" class="admin__page-section order-card-validation">
                <?= $block->getChildHtml('card_validation') ?>
            </section>
        <?php endif; ?>

        <section class="admin__page-section order-summary">
            <div class="admin__page-section-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Quote Total') ?></span>
            </div>
            <div class="admin__page-section-content">
                <fieldset class="admin__fieldset order-history" id="order-comment">
                    <legend class="admin__legend"><span><?= /* @escapeNotVerified */ __('Quote History') ?></span></legend>
                    <br>
                    <?= $block->getChildHtml('comment') ?>
                </fieldset>
                <fieldset id="quote-totals" class="admin__fieldset order-totals">
                    <?= $block->getChildHtml('totals') ?>
                </fieldset>
            </div>
        </section>
    </div>

    <?php if ($block->getCustomerId()): ?>
        <div class="order-sidebar">
            <div class="store-switcher order-currency">
                <label class="admin__field-label" for="currency_switcher">
                    <?= /* @escapeNotVerified */ __('Quote Currency:') ?>
                </label>
                <select id="currency_switcher"
                        class="admin__control-select"
                        name="order[currency]"
                        onchange="quote.setCurrencyId(this.value); quote.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
                    <?php foreach ($block->getAvailableCurrencies() as $_code): ?>
                        <option value="<?= /* @escapeNotVerified */ $_code ?>"<?php if ($_code == $block->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?> symbol="<?= /* @escapeNotVerified */ $block->getCurrencySymbol($_code) ?>">
                            <?= /* @escapeNotVerified */ $block->getCurrencyName($_code) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="customer-current-activity" id="order-sidebar">
                <?= $block->getChildHtml('sidebar') ?>
            </div>
        </div>
    <?php endif; ?>

</div>
