<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
?>
<?php
$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
$dataHelper = $this->helper('MGS\RealReview\Helper\Data');
?>
<?php if (count($_items)):?>
    <div class="block review-list" id="customer-reviews">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo __('Customer Reviews') ?></strong>
        </div>
        <div class="block-content">
            <div class="toolbar review-toolbar">
                <?php echo $block->getChildHtml('toolbar') ?>
            </div>
            <ol class="items review-items">
                <?php foreach ($_items as $_review):?>
                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                        <div class="review-title" itemprop="name"><?php echo $block->escapeHtml($_review->getTitle()) ?></div>
                        <?php if (count($_review->getRatingVotes())): ?>
                            <div class="review-ratings">
                                <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                        <span class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                            <meta itemprop="worstRating" content = "1"/>
                                            <meta itemprop="bestRating" content = "100"/>
                                            <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                                            </span>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                        <div class="review-content" itemprop="description">
                            <?php echo nl2br($block->escapeHtml($_review->getDetail())) ?>
                        </div>
                        <div class="review-details">
                            <p class="review-author">
                                <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Review by')?></span>
                                <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
                            </p>
                            <p class="review-date">
                                <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                                <time class="review-details-value" itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>"><?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?></time>
                            </p>
                        </div>
                        <?php if (($dataHelper->customerLoggedIn()) && ($dataHelper->isEnable()) && ($dataHelper->getCustomerId() == $_review->getCustomerId())): ?>
                            <div class="review-action">
                                <div class="review-edit" id="review-edit">
                                    <a href="#"><?php echo __("Edit"); ?></a>
                                </div>
                                <div class="review-remove review-remove-<?= $_review->getReviewId(); ?>" id="review-remove">
                                    <?php if ($dataHelper->useAjax()): ?>
                                        <?php $urlDelRedirectAjax = $this->getUrl()."review/product/listAjax/id/".$this->getProductId()."/?p=1" ?>
                                        <a data-reviewid="<?= $_review->getReviewId() ?>" data-url="<?= $urlDelRedirectAjax ?>" href="javascript:void(0)"><?php echo __("Delete"); ?></a>
                                    <?php else: ?>
                                        <a href="<?php echo $this->getUrl('mgsrealreview/index/delete/',['review_id' => $_review->getReviewId()]); ?>"><?php echo __("Delete"); ?></a>
                                        <script type="text/javascript">
                                            require([
                                                'jquery',
                                                'mage/translate',
                                                'Magento_Ui/js/modal/confirm'
                                            ], function($,$t,confirmation) {
                                                $('.review-remove > a').click(function() {
                                                    var url = event.currentTarget.href;
                                                    confirmation({
                                                        content: $t("Do you want remove your review?"),
                                                        modalClass: "confirm-delete-review",
                                                        actions: {
                                                            confirm: function(){
                                                                window.location.href = url;
                                                            },
                                                            cancel: function(){},
                                                            always: function() {}
                                                        }
                                                    });
                                                    return false;
                                                });
                                            });
                                        </script>
                                    <?php endif ?>

                                </div>
                            </div>
                        <?php endif ?>
                        <?php if ($dataHelper->isEnable()): ?>
                            <?php foreach ($block->getReviewAnswer($_review->getReviewId()) as $answer): ?>
                                <?php if (!empty($answer['review_answer'])): ?>
                                    <div class="review-answer">
                                        <p class="review-answer-title"><?php  echo __('Response from store'); ?></p>
                                        <div class="review-answer-content">
                                            <?php
                                            $content = $answer['review_answer'];
                                            echo $block->filterOutputHtml($content);
                                            ?>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php endforeach ?>
                        <?php endif ?>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="toolbar review-toolbar">
                <?php echo $block->getChildHtml('toolbar') ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        require(['jquery'],function($) {
            $('[data-role="product-review"] .pages a').click(function (event) {
                $('#product-review-container .block-content').addClass('review-ajax-loading');
                event.preventDefault();
            });
        });
    </script>
<?php endif;?>
