<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php

/** @var $block \Amasty\RequestQuote\Block\Account\Quote\Item\Price\Renderer */

$item = $block->getItem();
?>
<?= /* @noEscape */ $item->getNotes() && $item->getNotes()->getRequestedPrice()
    ? $block->convertPrice($item->getNotes()->getRequestedPrice(), true)
    : $block->escapeHtml(__('N/A'))
?>
