<style>
    #team .col{
        float: left;
        width: 250px;
        border:1px solid #0cc;
        padding: 3px;
        margin-left: 10px;
        height: 250px;
        margin-top: 10px;
    }
    .col img{
        border: 1px solid orange;
        padding: 3px;
        width: 150px;
        height: 150px;
        margin-left: 45px;
    }
    .cls{
        clear: left;
        margin-bottom: 5px;
    }
    .col h4{
        color: white;
        background: green;
        text-align:center;
        padding: 3px;
    }
    #team .limiter {
        display: block;
    }
</style>
<div id="team">
    <?php
    $break=3;
    $urlMedia=$this->getBaseUrlMedia();
    $staffs=$this->getStaffList();
    $i=1;
    ?>
    <?php if ($staffs->getSize()): ?>
        <?php foreach ($staffs as $staff): ?>
            <?php $i++; ?>
            <div class='col'>
                <h4><?php echo $staff['name']; ?></h4>
                <img src="<?php echo $urlMedia.$staff['avatar'] ?>" width="150" height="150" alt="" />
                <p align="center"><b><?php echo $staff['position']; ?></b></p>
            </div>
            <?php if ($i > $break): ?>
                <?php $i = 1; ?>
                <div class='cls'></div>
            <?php endif ?>
        <?php endforeach ?>
        <div class='cls'></div>
        <div class="order-products-toolbar toolbar bottom">
        <?php echo $this->getPager(); ?>
        </div>
    <?php else: ?>
        <div class='message info empty'><span><?php echo __("You have no staff") ?></span></div>
    <?php endif ?>
</div>