<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<div class="admin__page-section-title">
    <strong class="title"><?= /* @escapeNotVerified */ $block->getHeaderText() ?></strong>
    <div class="actions" style="float: right;">
        <?= $block->getButtonsHtml() ?>
    </div>
</div>
<?= $block->getChildHtml() ?>
