<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/** @var \Amasty\RequestQuote\Block\Cart\Quote\Move $block */
?>
<a href="#"
   data-post='<?= /* @noEscape */ $block->getPostData() ?>'
   class="amquote-addto-button amasty-quote-link"
   amcart-observed="true"><?= $block->escapeHtml(__('Request a Quote')) ?>
</a>
