<div id="cart-page">
	<div id="block-cart-list" data-bind="scope:'minicart-addons'" class="block">
		<!-- ko template: getTemplate() --><!-- /ko -->
		<script>
			maxpriceShipping = <?= /* @escapeNotVerified */ $this->getConfigForShippingBar() ?>;
		</script>
		<script type="text/x-magento-init">
			{
				"#block-cart-list": {
					"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
				},
				"*": {
					"Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
				}
			}
		</script>
	</div>
</div>