<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php /** @var \Amasty\RequestQuote\Block\Adminhtml\Quote\Edit\Items\Discounts $block */ ?>
<div class="amquote-field-block">
    <label for="discount" class="amquote-label"><?= $block->escapeHtml(__('Additional Discount (%)')) ?></label>
    <input id="discount"
           name="quote[discount]"
           data-price-modificator="discount"
           value="<?= $block->escapeHtml(sprintf("%.2f", $block->getAppliedDiscount())) ?>"
           class="amquote-input admin__control-text validate-digits-range digits-range-0-100"
           type="number"
           step="1"
           min="0"
           max="100"
        <?= /* @noEscape */ $block->getAppliedSurcharge() ? 'disabled' : '' ?> />
</div>
<div class="amquote-field-block">
    <label for="surcharge" class="amquote-label"><?= $block->escapeHtml(__('Additional Surcharge (%)')) ?></label>
    <input id="surcharge"
           name="quote[surcharge]"
           data-price-modificator="surcharge"
           value="<?= $block->escapeHtml(sprintf("%.2f", $block->getAppliedSurcharge())) ?>"
           class="amquote-input admin__control-text validate-digits-range digits-range-0-100"
           type="number"
           step="1"
           min="0"
           max="100"
        <?= /* @noEscape */ $block->getAppliedDiscount() ? 'disabled' : '' ?> />
</div>
