<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php $item = $block->getItem() ?>
<?php $_quote = $block->getQuote() ?>

<?php if ($block->getOptionList() || $item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<tr class="bundle-item bundle-parent">
    <td class="item-info">
        <p class="product-name"><?= $block->escapeHtml($item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */ __('SKU') ?>: <?= $block->escapeHtml($item->getSku()) ?></p>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */ $item->getQty() * 1 ?></td>
    <td class="item-price"><?= /* @escapeNotVerified */ $block->getUnitPriceHtml($item) ?></td>
</tr>

<?php if ($_showlastRow): ?>
    <tr>
        <td colspan="3" class="item-extra">
            <?php if ($block->getOptionList()): ?>
                <dl>
                    <?php foreach ($block->getOptionList() as $option): ?>
                        <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                        <dd><?= /* @escapeNotVerified */  implode(',', $option['value']) ?></dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
